###
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:

- name: unit test
  image: golang
  commands:
    - go test ./... 

- name: publish to Dockerhub image
  image: plugins/docker
  settings:
    auto_tag: true
    repo: thomaslacaze/wakapi-stats
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
    branch:
    - master
    - main

- name: publish readme to Dockerhub
  image: thomaslacaze/dockerhub-description:2.4.1
  pull: always
  settings:
    repository: thomaslacaze/wakapi-stats
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    readme: /drone/src/README.md
  when:
    branch:
    - master
    - main


- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
    usingProperties: sonar-project.properties
###